include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
