name: riverpod_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.5.0
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.0.3
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
